export const WORDS = [
  { word: "CAT", hint: "A small furry pet that purrs" },
  { word: "DOG", hint: "A loyal pet that barks" },
  { word: "SUN", hint: "The bright star in our sky" },
  { word: "MOON", hint: "It shines in the night sky" },
  { word: "STAR", hint: "A twinkling light in space" },
  { word: "TREE", hint: "A tall plant with a trunk and leaves" },
  { word: "BIRD", hint: "An animal with wings and feathers" },
  { word: "FISH", hint: "An animal that swims underwater" },
  { word: "FROG", hint: "A green amphibian that hops" },
  { word: "BEAR", hint: "A large, furry forest animal" },
  { word: "LION", hint: "The king of the jungle" },
  { word: "TIGER", hint: "A large orange cat with black stripes" },
  { word: "DUCK", hint: "A bird that quacks and swims" },
  { word: "SWAN", hint: "A graceful white water bird" },
  { word: "APPLE", hint: "A crunchy red or green fruit" },
  { word: "GRAPE", hint: "A small purple or green fruit" },
  { word: "LEMON", hint: "A sour yellow fruit" },
  { word: "MELON", hint: "A large, sweet fruit" },
  { word: "PEACH", hint: "A fuzzy, sweet fruit" },
  { word: "BERRY", hint: "A small, juicy fruit like a strawberry" },
  { word: "BREAD", hint: "Baked food made from dough" },
  { word: "CHEESE", hint: "A yellow or white dairy food" },
  { word: "MILK", hint: "A white drink from cows" },
  { word: "WATER", hint: "A clear liquid we drink to stay hydrated" },
  { word: "JUICE", hint: "A sweet drink made from fruits" },
  { word: "CAKE", hint: "A sweet baked dessert" },
  { word: "CANDY", hint: "A sweet treat" },
  { word: "HOUSE", hint: "A building where people live" },
  { word: "DOOR", hint: "You open this to enter a room" },
  { word: "WINDOW", hint: "Glass opening to see outside" },
  { word: "CHAIR", hint: "A piece of furniture you sit on" },
  { word: "TABLE", hint: "Furniture with a flat top and legs" },
  { word: "BED", hint: "Where you sleep at night" },
  { word: "SOFA", hint: "A comfortable seat for multiple people" },
  { word: "CLOCK", hint: "A device that tells time" },
  { word: "WATCH", hint: "A small clock worn on the wrist" },
  { word: "PHONE", hint: "A device used to call people" },
  { word: "BOOK", hint: "Pages with words to read" },
  { word: "PENCIL", hint: "Used for writing or drawing" },
  { word: "PAPER", hint: "What you write on" },
  { word: "TRAIN", hint: "Vehicles connected together on tracks" },
  { word: "PLANE", hint: "A vehicle that flies in the sky" },
  { word: "BOAT", hint: "A vehicle that floats on water" },
  { word: "SHIP", hint: "A large boat" },
  { word: "CAR", hint: "A road vehicle with four wheels" },
  { word: "TRUCK", hint: "A large vehicle for transporting goods" },
  { word: "BUS", hint: "A large vehicle that carries many passengers" },
  { word: "BIKE", hint: "A two-wheeled vehicle you pedal" },
  { word: "SHOE", hint: "You wear this on your foot" },
  { word: "SOCK", hint: "Worn on the foot inside a shoe" },
  { word: "SHIRT", hint: "Clothing worn on the upper body" },
  { word: "PANTS", hint: "Clothing worn on the lower body" },
  { word: "DRESS", hint: "A one-piece garment for women or girls" },
  { word: "HAT", hint: "Worn on the head" },
  { word: "COAT", hint: "Warm clothing worn outdoors" },
  { word: "GLOVE", hint: "Worn on the hand to keep it warm" },
  { word: "HAPPY", hint: "Feeling joyful" },
  { word: "SAD", hint: "Feeling unhappy" },
  { word: "ANGRY", hint: "Feeling mad" },
  { word: "BRAVE", hint: "Showing no fear" },
  { word: "SMART", hint: "Very intelligent" },
  { word: "FAST", hint: "Moving quickly" },
  { word: "SLOW", hint: "Moving without speed" },
  { word: "LOUD", hint: "Making a lot of noise" },
  { word: "QUIET", hint: "Making little or no noise" },
  { word: "TALL", hint: "Of great height" },
  { word: "SHORT", hint: "Small in height" },
  { word: "BIG", hint: "Large in size" },
  { word: "SMALL", hint: "Little in size" },
  { word: "COLD", hint: "Having a low temperature" },
  { word: "HOT", hint: "Having a high temperature" },
  { word: "RAIN", hint: "Water falling from clouds" },
  { word: "SNOW", hint: "White ice flakes falling from the sky" },
  { word: "WIND", hint: "Moving air" },
  { word: "CLOUD", hint: "A white or gray mass in the sky" },
  { word: "STORM", hint: "Bad weather with heavy rain and wind" },
  { word: "OCEAN", hint: "A vast body of salt water" },
  { word: "RIVER", hint: "A flowing body of water" },
  { word: "LAKE", hint: "A large body of water surrounded by land" },
  { word: "BEACH", hint: "Sandy shore by the ocean" },
  { word: "MOUNTAIN", hint: "A very high hill" },
  { word: "FOREST", hint: "A large area covered with trees" },
  { word: "DESERT", hint: "A very dry, sandy area" },
  { word: "ISLAND", hint: "Land surrounded by water" },
  { word: "MAGIC", hint: "Sorcery or illusion" },
  { word: "GHOST", hint: "A spooky spirit" },
  { word: "WITCH", hint: "A woman with magical powers" },
  { word: "FAIRY", hint: "A small magical creature with wings" },
  { word: "DRAGON", hint: "A mythical fire-breathing reptile" },
  { word: "KING", hint: "The male ruler of an empire" },
  { word: "QUEEN", hint: "The female ruler of an empire" },
  { word: "PRINCE", hint: "The son of a king and queen" },
  { word: "CASTLE", hint: "A large fortified building" },
  { word: "SWORD", hint: "A weapon with a long metal blade" },
  { word: "SHIELD", hint: "Used to protect against attacks" },
  { word: "CROWN", hint: "Worn on the head by a king or queen" },
  { word: "GOLD", hint: "A precious yellow metal" },
  { word: "SILVER", hint: "A shiny gray metal" },
  { word: "GEM", hint: "A precious stone" },
  { word: "RING", hint: "A small circular band worn on a finger" }
];
